version: "3.7"
services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: app:1.0
        container_name: app
        ports:
            - 5173:5173
        restart: unless-stopped
        volumes:
            - ./:/var/www/app
            - ./docker/php/conf.d:/usr/local/etc/php/conf.d
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DB_HOST=host.docker.internal
        networks:
            - uth
    db:
        image: mariadb:10.3
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: database
        ports:
            - 3306:3306
        volumes:
            - ./docker/mariadb/conf.d:/etc/mysql/conf.d
            - ./docker/mariadb/dump:/docker-dump
        networks:
            - uth
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: nginx:1.0
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
            - ./docker/nginx/data:/etc/nginx/data/
        networks:
            - uth
    redis:
        image: redis:6.2
        container_name: redis
        networks:
            - uth

networks:
    uth:
        driver: bridge
